---
title: "Forecast skill"
author: "Shaun Harrigan"
output: html_document
---

#### Worked Example 13.1

## Loading the data

In this example we will be calculating the *skill* of the Ensemble Streamflow Prediction (ESP) forecast method
for the Lambourn catchment at Shaw gauging station in southern England (catchment area of 234.1 km^2^). 
The dataset consists of monthly-averaged river discharge observations and ESP forecasts initialised on 1^st^ January for a one month lead time
across the 1965 to 2014 hindcast period. The 50 forecasts each contain 51 ensemble members.
The units for both observations and forecasts are m^3^s^-1^.
More detail on how these data were generated can be found in Harrigan et al. (2018).

First we load the dataset and create the variables we will use in later calculations:

```{r}
# Load the data 
inFolder <- "/Users/shaunharrigan/Dropbox/Projects/Drought_book/Worked_example/Data/"
fcst_dataset <- read.csv(paste0(inFolder, "forecast_data.csv"), header = TRUE) 
dim(fcst_dataset) # Check dimentions of dataset

# Subset observations vector 
obs <- fcst_dataset$Observed_flow

# Subset ensemble forecast matrix
fcst_ens <- fcst_dataset[ ,3:53]

# Plot observed and ensemble forecast
boxplot(t(fcst_ens), xlab = "Hindcast year", ylab = "Flow (cumecs)")
lines(obs, col = "red")
```

## Calculate low flow index from observations 


XXX

## Evaluate ability of ESP to forecast low flows


XXX

## End

